fiximports:golang.org/x/tools/cmd/...
godef:github.com/rogpeppe/godef/...
gocode:github.com/nsf/gocode
goimports:golang.org/x/tools/cmd/goimports
guru:golang.org/x/tools/cmd/guru
goflymake:github.com/dougm/goflymake
